---
project_name: werkzeugkasten
env:
  - CGO_ENABLED=0
builds:
  - binary: werkzeugkasten
    id: werkzeugkasten
    main: ./
    ldflags:
      - -X main.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  algorithm: sha256
changelog:
  skip: false
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^ci:"
release:
  name_template: "{{ .ProjectName }}-{{ .Version }}"
  header: |
    ## {{ .Version }} ({{ .Date }})
    New {{ .Version }} release!
