---
version: "3"

tasks:
  default:
    silent: true
    cmds:
      - task -l

  install:
    desc: Install App
    cmds:
      - task: fmt
      - task: lint
      - task: vet
      - task: build
      - go install -ldflags "-s -w -X github.com/allaman/werkzeugkasten/cli.Version=dev"

  build:
    desc: Build App
    cmds:
      - go build

  run:
    desc: Run App
    cmds:
      - go build && ./werkzeugkasten

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run .

  fmt:
    desc: Run formatter
    cmds:
      - go fmt .

  upgrade-deps:
    desc: Upgrade all dependencies
    cmds:
      - go get -u ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet

  vuln:
    desc: Check for vulnerabilities
    cmds:
      - govulncheck .

  nix-flake:
    desc: Lock and validate flake via Docker
    summary: This will likey fail on first run. Copy the vendor hash and update the hash in flake.nix. Then run again and there should be no error.
    cmds:
      - docker run --rm -it -v "$PWD":/work -w /work nixos/nix:latest sh -lc 'nix --extra-experimental-features "nix-command flakes" flake lock && nix --extra-experimental-features "nix-command flakes" build'
